title: routine exam
description: University of Nagasaki
theme: jekyll-theme-minimal
lsi: false
safe: true
source: 4072231/4072231.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
